import { GoogleGenerativeAI } from '@google/generative-ai'
import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '')
const MODEL = 'gemini-3.5-flash'

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
)

// ── PROMPTS ────────────────────────────────────────────────────────────────

const TEXT_PROMPT = `You are a rigorous, unbiased content analyst. Examine the text and determine:
1. Whether it was likely written by a human or generated by AI
2. What rhetorical or manipulation techniques are present (if any)
3. Whether factual claims appear verifiable or fabricated

Rules:
- Be strictly fact-based. No political, cultural, or ideological bias.
- If uncertain, say so clearly. Never overstate confidence.
- Cite specific phrases as evidence.

Return ONLY raw JSON (no markdown, no code fences):
{
  "aiProbability": <integer 0-100>,
  "summary": "<1 sentence plain-language verdict>",
  "flags": ["<short signal strings>"],
  "reasoning": "<2-3 sentences citing specific evidence>",
  "deepReport": {
    "originAssessment": "<paragraph: writing style, syntax, vocabulary analysis>",
    "rhetoricalTechniques": "<paragraph: persuasion/manipulation techniques with direct quotes>",
    "factualClaims": "<paragraph: key claims and whether they are verifiable>",
    "overallVerdict": "<paragraph: final balanced credibility verdict>"
  }
}`

const LINK_PROMPT = `You are a rigorous, unbiased link-safety analyst. Assess the URL for safety.

Rules:
- Analyze only from URL structure: domain, subdomains, TLD, path, params.
- Be fact-based. Do not flag legitimate sites without evidence.
- If legitimate and safe, say so clearly.

Return ONLY raw JSON (no markdown, no code fences):
{
  "aiProbability": <integer 0-100 risk score>,
  "summary": "<1 sentence plain-language verdict>",
  "flags": ["<structural red flags or trust signals>"],
  "reasoning": "<2 sentences explaining the score>",
  "deepReport": {
    "domainAnalysis": "<paragraph: domain breakdown, TLD, lookalike patterns>",
    "pathAnalysis": "<paragraph: path and query params analysis>",
    "trustSignals": "<paragraph: indicators of legitimacy or illegitimacy>",
    "overallVerdict": "<paragraph: final safety assessment with evidence>"
  }
}`

const IMAGE_PROMPT = `You are a rigorous, unbiased image authenticity analyst. Determine if this image is AI-generated.

Rules:
- Base analysis strictly on observable visual evidence.
- Be specific: cite exact regions or artifacts you see.
- Be honest about uncertainty.
- Only include factualityScore and factualClaims if the image contains a visible paragraph or significant block of readable text. Otherwise set factualityScore to null and factualClaims to [].

Return ONLY raw JSON (no markdown, no code fences):
{
  "aiProbability": <integer 0-100>,
  "summary": "<1 sentence plain-language verdict>",
  "flags": ["<specific visual observations>"],
  "reasoning": "<2-3 sentences citing specific visual evidence>",
  "factualityScore": <integer 0-100 or null if no readable text in image>,
  "factualClaims": [],
  "deepReport": {
    "anatomicalAnalysis": "<paragraph: hands, faces, eyes, hair assessment>",
    "lightingAndShadows": "<paragraph: consistency of lighting and shadows>",
    "textureAndDetail": "<paragraph: skin, fabric, background texture analysis>",
    "overallVerdict": "<paragraph: final authenticity verdict with visual evidence>"
  }
}`

// ── MAIN HANDLER ───────────────────────────────────────────────────────────

export async function POST(req: Request) {
  try {
    const { text, imageUrl, imageBase64, imageMimeType, userId } = await req.json()

    let result: any

    if (imageUrl || imageBase64) {
      result = await analyzeImage(imageUrl, imageBase64, imageMimeType)
      result.contentType = 'image'
      result.subject = imageUrl ?? 'uploaded image'
    } else if (text && typeof text === 'string') {
      const trimmed = text.trim()
      const isLink = /^https?:\/\/\S+$/i.test(trimmed)
      if (isLink) {
        result = await analyzeLink(trimmed)
        result.contentType = 'link'
        result.subject = trimmed
      } else {
        result = await analyzeText(trimmed)
        result.contentType = 'text'
        result.subject = trimmed.slice(0, 200)
      }
    } else {
      return NextResponse.json({ error: 'Missing "text" or "imageUrl" field' }, { status: 400 })
    }

    // Save full report to DB — one row per user, replaced on every analysis
    if (userId) {
      await supabaseAdmin
        .from('analysis_results')
        .upsert({
          user_id: userId,
          content_type: result.contentType,
          subject: result.subject,
          ai_probability: result.aiProbability,
          verdict: result.summary,
          summary_flags: result.flags,
          summary_reason: result.reasoning,
          deep_analysis: result.deepReport,
          cross_checks: [],
          confidence: 'medium',
          analyzed_at: new Date().toISOString(),
        }, { onConflict: 'user_id' })
    }

    return NextResponse.json(result)
  } catch (err: any) {
    console.error('analyze-content error:', err?.message ?? err)
    return NextResponse.json({ error: err.message || 'Analysis failed' }, { status: 500 })
  }
}

// ── GET — fetch latest saved result for a user ─────────────────────────────
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url)
  const userId = searchParams.get('userId')
  if (!userId) return NextResponse.json({ error: 'Missing userId' }, { status: 400 })

  const { data, error } = await supabaseAdmin
    .from('analysis_results')
    .select('*')
    .eq('user_id', userId)
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 404 })
  return NextResponse.json(data)
}

// ── ANALYZERS ──────────────────────────────────────────────────────────────

async function analyzeText(text: string) {
  const model = genAI.getGenerativeModel({ model: MODEL })
  const result = await model.generateContent(`${TEXT_PROMPT}\n\nText to analyze:\n"""\n${text}\n"""`)
  return shape(safeParseJson(result.response.text().trim()))
}

async function analyzeLink(url: string) {
  const model = genAI.getGenerativeModel({ model: MODEL })
  const result = await model.generateContent(`${LINK_PROMPT}\n\nURL to analyze:\n${url}`)
  return shape(safeParseJson(result.response.text().trim()))
}

async function analyzeImage(imageUrl?: string, imageBase64?: string, imageMimeType?: string) {
  let imagePart: any

  if (imageBase64 && imageMimeType) {
    imagePart = { inlineData: { data: imageBase64, mimeType: imageMimeType } }
  } else if (imageUrl) {
    try {
      const res = await fetch(imageUrl, {
        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' },
        signal: AbortSignal.timeout(10000),
      })
      if (!res.ok) throw new Error(`Failed to fetch image: ${res.status}`)
      const buffer = await res.arrayBuffer()
      const ct = res.headers.get('content-type') || 'image/jpeg'
      imagePart = { inlineData: { data: Buffer.from(buffer).toString('base64'), mimeType: ct.split(';')[0].trim() } }
    } catch {
      return analyzeText(`Image URL for analysis: ${imageUrl}`)
    }
  } else {
    return shape({})
  }

  const model = genAI.getGenerativeModel({ model: MODEL })
  const result = await model.generateContent([
    `${IMAGE_PROMPT}\n\nAnalyze this image:`,
    imagePart,
  ])
  const parsed = safeParseJson(result.response.text().trim())
  // Guard: if no factual claims found, force factualityScore to null
  if (!parsed.factualClaims || parsed.factualClaims.length === 0) {
    parsed.factualityScore = null
    parsed.factualClaims = []
  }
  return shape(parsed)
}

// ── HELPERS ────────────────────────────────────────────────────────────────

function shape(parsed: any) {
  return {
    aiProbability: parsed.aiProbability ?? 50,
    summary: parsed.summary ?? 'Analysis complete.',
    flags: parsed.flags ?? [],
    reasoning: parsed.reasoning ?? '',
    deepReport: parsed.deepReport ?? null,
    biasFlags: parsed.flags ?? [],   // legacy compat for extension NutritionCard
    factCheckRefs: [],
  }
}

function safeParseJson(raw: string): any {
  // Strip markdown code fences Gemini sometimes wraps around JSON
  const stripped = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/m, '').trim()
  try { return JSON.parse(stripped) } catch { /* fall through */ }
  const match = stripped.match(/\{[\s\S]*\}/)
  if (match) { try { return JSON.parse(match[0]) } catch { /* fall through */ } }
  console.error('safeParseJson failed, raw response:', raw.slice(0, 500))
  return {}
}
