import { GoogleGenerativeAI } from '@google/generative-ai'
import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '')

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
)

// ── PROMPTS ────────────────────────────────────────────────────────────────
// All prompts share the same philosophy:
//   - Fact-based only. No political, cultural, or ideological bias.
//   - If evidence is insufficient, say so honestly.
//   - Two outputs: a short summary for the overlay card, and a deep report
//     for the web app detail view.

const TEXT_PROMPT = `You are a rigorous, unbiased content analyst. Your job is to examine text and determine:
1. Whether it was likely written by a human or generated by AI
2. What rhetorical or manipulation techniques are present (if any)
3. Whether factual claims can be verified or appear fabricated

Rules:
- Be strictly fact-based. Do not introduce political, cultural, or ideological bias.
- If you are uncertain, say so clearly. Never overstate confidence.
- Cite specific phrases or patterns from the text as evidence.
- Do not assume malicious intent without evidence.

Return ONLY a valid JSON object (no markdown, no code fences):
{
  "aiProbability": <integer 0-100, likelihood text is AI-generated>,
  "summary": "<1 sentence plain-language verdict for the overlay card>",
  "flags": [<short strings: detected manipulation techniques or quality signals, e.g. "Emotional manipulation", "Unverifiable claim", "Formal AI phrasing", "Personal anecdote — human indicator">],
  "reasoning": "<2-3 sentences: concise explanation citing specific evidence from the text>",
  "deepReport": {
    "originAssessment": "<paragraph: detailed analysis of writing style, syntax patterns, vocabulary choices that inform the AI vs human verdict>",
    "rhetoricalTechniques": "<paragraph: identify and explain any persuasion or manipulation techniques found, with direct quotes from the text as evidence>",
    "factualClaims": "<paragraph: list key factual claims made in the text and assess whether they are verifiable, likely true, likely false, or unverifiable>",
    "overallVerdict": "<paragraph: final balanced verdict on credibility and trustworthiness of this content, with specific reasoning>"
  }
}`

const LINK_PROMPT = `You are a rigorous, unbiased link-safety analyst. Your job is to assess a URL for safety and trustworthiness.

Rules:
- Analyze only what can be determined from the URL structure: domain, subdomains, TLD, path, query params.
- Be fact-based. Do not flag legitimate sites without evidence.
- Cite specific structural elements as evidence for your assessment.
- If the URL appears legitimate and safe, say so clearly.

Return ONLY a valid JSON object (no markdown, no code fences):
{
  "aiProbability": <integer 0-100, overall risk score>,
  "summary": "<1 sentence plain-language verdict for the overlay card>",
  "flags": [<short strings: structural red flags or trust signals, e.g. "Lookalike domain", "Legitimate official domain", "URL shortener", "Suspicious path">],
  "reasoning": "<2 sentences: concise explanation of the risk score>",
  "deepReport": {
    "domainAnalysis": "<paragraph: detailed breakdown of the domain — registrar patterns, TLD choice, subdomain tricks, similarity to known brands>",
    "pathAnalysis": "<paragraph: analyze the URL path and query parameters for urgency bait, phishing patterns, or suspicious tokens>",
    "trustSignals": "<paragraph: list any indicators that suggest this is a legitimate or illegitimate URL>",
    "overallVerdict": "<paragraph: final safety assessment with specific evidence-based reasoning>"
  }
}`

const IMAGE_PROMPT = `You are a rigorous, unbiased image authenticity analyst. Your job is to determine whether an image is AI-generated or a genuine photograph.

Rules:
- Base your analysis strictly on observable visual evidence in the image.
- Be specific: cite exact regions, objects, or artifacts you observe.
- Be honest about uncertainty — many real photos have imperfections, and many AI images look realistic.
- Do not assume AI generation without observable evidence.

Return ONLY a valid JSON object (no markdown, no code fences):
{
  "aiProbability": <integer 0-100, likelihood image is AI-generated or synthetically manipulated>,
  "summary": "<1 sentence plain-language verdict for the overlay card>",
  "flags": [<short strings: specific visual observations, e.g. "Distorted fingers", "Consistent lighting — human indicator", "Unnatural skin texture", "Background artifacts">],
  "reasoning": "<2-3 sentences: concise explanation citing specific visual evidence>",
  "deepReport": {
    "anatomicalAnalysis": "<paragraph: assess hands, faces, eyes, hair, teeth — common AI failure points — with specific observations>",
    "lightingAndShadows": "<paragraph: evaluate consistency of light sources, shadow directions, and reflections across the image>",
    "textureAndDetail": "<paragraph: assess fine textures — fabric, skin, hair, backgrounds — for AI-characteristic smoothing or repetition artifacts>",
    "overallVerdict": "<paragraph: final balanced verdict on authenticity with specific visual evidence cited>"
  }
}`

// ── MAIN HANDLER ───────────────────────────────────────────────────────────

export async function POST(req: Request) {
  try {
    const { text, imageUrl, imageBase64, imageMimeType, userId } = await req.json()

    let result: any

    if (imageUrl || imageBase64) {
      result = await analyzeImage(imageUrl, imageBase64, imageMimeType)
      result.contentType = 'image'
      result.subject = imageUrl ?? 'uploaded image'
    } else if (text && typeof text === 'string') {
      const trimmed = text.trim()
      const isLink = /^https?:\/\/\S+$/i.test(trimmed)
      if (isLink) {
        result = await analyzeLink(trimmed)
        result.contentType = 'link'
        result.subject = trimmed
      } else {
        result = await analyzeText(trimmed)
        result.contentType = 'text'
        result.subject = trimmed.slice(0, 200)
      }
    } else {
      return NextResponse.json({ error: 'Missing "text" or "imageUrl" field' }, { status: 400 })
    }

    // Save full report to DB (upsert per user — replaces previous result)
    if (userId) {
      await supabaseAdmin
        .from('analysis_results')
        .upsert({
          user_id: userId,
          content_type: result.contentType,
          subject: result.subject,
          ai_probability: result.aiProbability,
          summary: result.summary,
          flags: result.flags,
          reasoning: result.reasoning,
          deep_report: result.deepReport,
          analyzed_at: new Date().toISOString(),
        }, { onConflict: 'user_id' })
    }

    // Return the full result (web app uses deepReport, extension uses summary+flags+reasoning)
    return NextResponse.json(result)
  } catch (err: any) {
    console.error('analyze-content error:', err)
    return NextResponse.json({ error: err.message || 'Analysis failed' }, { status: 500 })
  }
}

// ── GET — fetch the latest saved result for a user ─────────────────────────
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url)
  const userId = searchParams.get('userId')
  if (!userId) return NextResponse.json({ error: 'Missing userId' }, { status: 400 })

  const { data, error } = await supabaseAdmin
    .from('analysis_results')
    .select('*')
    .eq('user_id', userId)
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 404 })
  return NextResponse.json(data)
}

// ── ANALYZERS ──────────────────────────────────────────────────────────────

async function analyzeText(text: string) {
  const model = genAI.getGenerativeModel({ model: 'gemini-3.5-flash-lite' })
  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: `${TEXT_PROMPT}\n\nText to analyze:\n"""\n${text}\n"""` }] }],
  })
  const parsed = safeParseJson(result.response.text().trim())
  return shape(parsed)
}

async function analyzeLink(url: string) {
  const model = genAI.getGenerativeModel({ model: 'gemini-3.5-flash-lite' })
  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: `${LINK_PROMPT}\n\nURL to analyze:\n${url}` }] }],
  })
  const parsed = safeParseJson(result.response.text().trim())
  return shape(parsed)
}

async function analyzeImage(imageUrl?: string, imageBase64?: string, imageMimeType?: string) {
  const model = genAI.getGenerativeModel({ model: 'gemini-3.5-flash-lite' })

  let imagePart: any

  if (imageBase64 && imageMimeType) {
    imagePart = { inlineData: { data: imageBase64, mimeType: imageMimeType } }
  } else if (imageUrl) {
    try {
      const res = await fetch(imageUrl, {
        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36' },
        signal: AbortSignal.timeout(10000),
      })
      if (!res.ok) throw new Error(`Failed to fetch image: ${res.status}`)
      const buffer = await res.arrayBuffer()
      const ct = res.headers.get('content-type') || 'image/jpeg'
      imagePart = { inlineData: { data: Buffer.from(buffer).toString('base64'), mimeType: ct.split(';')[0].trim() } }
    } catch {
      return analyzeText(`Image URL for analysis: ${imageUrl}`)
    }
  } else {
    return shape({})
  }

  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: `${IMAGE_PROMPT}\n\nAnalyze this image:` }, imagePart] }],
  })
  const parsed = safeParseJson(result.response.text().trim())
  return shape(parsed)
}

// Normalize response shape — extension only needs the top-level fields
function shape(parsed: any) {
  return {
    aiProbability: parsed.aiProbability ?? 50,
    summary: parsed.summary ?? 'Analysis complete.',
    flags: parsed.flags ?? [],
    reasoning: parsed.reasoning ?? '',
    deepReport: parsed.deepReport ?? null,
    // Legacy fields for backward compat with extension NutritionCard
    biasFlags: parsed.flags ?? [],
    factCheckRefs: [],
  }
}

function safeParseJson(raw: string): any {
  // Strip markdown code fences if present (```json ... ``` or ``` ... ```)
  const stripped = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()
  try { return JSON.parse(stripped) } catch { /* fall through */ }
  // Try to extract first {...} block
  const match = stripped.match(/\{[\s\S]*\}/)
  if (match) { try { return JSON.parse(match[0]) } catch { /* fall through */ } }
  return {}
}
